name: CI/CD Cypress

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'  # Confirme que a versão 22 é a correta para seu projeto

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        env:
          apiKey: ${{ secrets.APIKEY }}
          apiToken: ${{ secrets.APITOKEN }}
        run: |
          npx cypress run --env apiKey=${{ secrets.APIKEY }},apiToken=${{ secrets.APITOKEN }}
